name: Environment Publish

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-npm:
    name: Publish on npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn nx build environment
      - run: npm publish dist/packages/environment
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
