name: Deploy Package
description: Deploy project package

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup
      uses: ./.github/actions/setup

    - name: Build
      shell: bash
      run: yarn nx build ${{ env.PROJECT_NAME }}

    - name: Deploy in npm.js
      shell: bash
      run: npm publish dist/packages/${{ env.PROJECT_NAME }} --access=public
