name: Deploy Documentation
description: Deploy Kuoki project Documentation

inputs:
  github_token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - name: Generate Documentation
      shell: bash
      run: yarn nx docs ${{ env.PROJECT_NAME }}
    - name: Deploy Documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: docs/${{ env.PROJECT_NAME }}
        destination_dir: ${{ env.PROJECT_NAME }}
