name: Anymap Continuous Deployment

on:
  push:
    tags:
      - 'anymap-v*'
  workflow_dispatch:

env:
  PROJECT_NAME: anymap
  GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

concurrency:
  group: ci-anymap-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    name: Generate Reports and Analyze in SonarCloud
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sonar

  deploy_package:
    needs: sonarcloud
    runs-on: ubuntu-latest
    name: Generate and Deploy Package
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-package

  deploy_docs:
    needs: sonarcloud
    runs-on: ubuntu-latest
    name: Generate and Deploy Documentation
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-docs
