name: Environment Angular Continuous Integration and Deployment

on:
  workflow_dispatch:
  push:
    tags:
      - environment-angular-v*

env:
  PROJECT_NAME: environment-angular
  GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

concurrency:
  group: ci-environment-angular-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    name: Generate Reports and Analyze in SonarCloud
    steps:
      - uses: ./.github/actions/sonar

  deploy_package:
    needs: sonarcloud
    runs-on: ubuntu-latest
    name: Generate and Deploy Package
    steps:
      - uses: ./.github/actions/deploy-package

  deploy_docs:
    needs: sonarcloud
    runs-on: ubuntu-latest
    name: Generate and Deploy Documentation
    steps:
      - uses: ./.github/actions/deploy-docs
