name: Environment SonarCloud

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master
#  pull_request:
#    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Saionaro/extract-package-version@v1.1.1
        id: extract_version
        with:
          path: ./packages/environment/
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn nx test environment --code-coverage --coverageReporters lcov --coverageDirectory=./packages/environment --skip-nx-cache
      - run: sed -i 's#packages/environment/##g' packages/environment/lcov.info
      - run: yarn nx lint environment --format json --outputFile packages/environment/eslint.json --skip-nx-cache
      - run: sed -i 's#/home/runner/work/kuoki/kuoki#/github/workspace#g' packages/environment/eslint.json
      - uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/environment
          args: >
            -Dsonar.projectVersion=${{ steps.extract_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
