name: Kuoki Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ci-test-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 16, 17]
    name: Test Affected on NodeJS ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}
      - name: Test Affected
        run: yarn nx affected --target=test

  build-lint:
    runs-on: ubuntu-latest
    name: Build & Lint Affected
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Build Affected
        run: yarn nx affected --target=build
      - name: Lint Affected
        run: yarn nx affected --target=lint

  version:
    needs: [test, build-lint]
    runs-on: ubuntu-latest
    name: Generate Affected Versions
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Version Affected
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx affected --target=version --parallel=1
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
