name: Kuoki Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/*/src/**

concurrency:
  group: ci-kuoki-${{ github.ref }}-1
  cancel-in-progress: true

env:
  HUSKY: 0
  GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 16, 18]
    name: Test Affected on NodeJS ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}

      - name: Test Affected
        run: yarn nx affected --target=test

  build-lint:
    runs-on: ubuntu-latest
    name: Build & Lint Affected
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint Affected
        run: yarn nx affected --target=lint

      - name: Build Affected
        run: yarn nx affected --target=build

  version:
    needs: [test, build-lint]
    runs-on: ubuntu-latest
    name: Generate Affected Versions
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Version Affected
        run: npx nx affected --target=version --parallel=1
